window.currentLang='vi';window.getTranslatedText=function(key){return translations[currentLang][key]||key;}
var images=['https://i.ibb.co/C0gT2rp/projeto-cafe-gato-mourisco-Z8m-Gr-8-E7f4-unsplash.jpg','https://i.ibb.co/HXbrp66/projeto-cafe-gato-mourisco-Uz1-Rk85-VUW4-unsplash.jpg','https://i.ibb.co/sqXW5Lf/projeto-cafe-gato-mourisco-z-OVRgig-QMQA-unsplash.jpg','https://i.ibb.co/D5rD1qj/projeto-cafe-gato-mourisco-eq5-OMTg-ED4-unsplash.jpg','https://i.ibb.co/JH08gkp/projeto-cafe-gato-mourisco-6fo-Phyz6-QU-unsplash.jpg','https://i.ibb.co/R0LYsq5/projeto-cafe-gato-mourisco-q-EJd-MO6-Qml-Y-unsplash.jpg','https://i.ibb.co/4WC5LWz/projeto-cafe-gato-mourisco-Pjv-HCp-KPzho-unsplash.jpg','https://i.ibb.co/gRdpBB3/anton-shuvalov-GTz-Rv-LR6a-OU-unsplash.jpg','https://i.ibb.co/Lg2SCqc/projeto-cafe-gato-mourisco-yw-Ec-Uv-W4-Ha-U-unsplash.jpg','https://i.ibb.co/ByhYLQy/projeto-cafe-gato-mourisco-b-Forvtl-Lx-SA-unsplash.jpg'];const imageUrls=['https://i.ibb.co/jLBvcbF/OIG2-1.jpg','https://i.ibb.co/Wxhg96g/OIG2-3.jpg','https://i.ibb.co/Wxhg96g/OIG2-3.jpg','https://i.ibb.co/WWpWVdX/OIG4.jpg'];const randomIndex=Math.floor(Math.random()*imageUrls.length);const randomImage=imageUrls[randomIndex];const getRandomImageUrl=()=>imageUrls[Math.floor(Math.random()*imageUrls.length)];let farmsNeedingAttention=new Set();let totalCurrentProd=0;let totalExpectedProd=0;const fetchFarmData3D=async(userIds)=>{try{const requests=userIds.map(userId=>axios.post('https://api-router.enfarm.com/api/v3/farm/total-farms-per-user',{user_id:userId},{headers:{'accept':'application/json','Content-Type':'application/json'}}));const responses=await axios.all(requests);const farms=responses.flatMap(response=>response.data.content.data);const farmNames=farms.map(farm=>farm.farm_name);fetch('https://api-ma.enfarm.com/api/v1/ma/get-install-locations',{headers:{'accept':'application/json'},}).then(response=>response.json()).then(async data=>{const filteredLocations=data.content.filter(location=>{return!(/toàn|test|enfarm|koko/i.test(location.farmname)||/toàn|test|enfarm|koko/i.test(location.region_name))&&farmNames.includes(location.farmname);});const associatedLocations=filteredLocations.filter(location=>{return farmNames.includes(location.farmname);});const uniqueFarms=new Set();filteredLocations.forEach(location=>{const farmKey=`${location.lat},${location.long}`;uniqueFarms.add(farmKey);});const uniqueFarmCount=uniqueFarms.size;document.getElementById('totalfarmCount').innerText=uniqueFarmCount;var totalDevicesCount=associatedLocations.length;var farmsNeedingAttentionCount=0;associatedLocations.forEach(async location=>{const excludedWords=["toàn","test","enfarm","koko"];const farmNameContainsExcludedWord=excludedWords.some(word=>location.farmname.toLowerCase().includes(word.toLowerCase()));const regionNameContainsExcludedWord=excludedWords.some(word=>location.region_name.toLowerCase().includes(word.toLowerCase()));if(farmNameContainsExcludedWord||regionNameContainsExcludedWord){return;}
const elevation=await getElevation(location.long,location.lat);const prefix='(';const suffix=')';const elevationDisplay=elevation?`<span class="material-symbols-outlined" style="font-size: 14px; margin-bottom: 2px;">${prefix}elevation</span> ${elevation.toFixed(0)} meters${suffix}`:`<span class="material-symbols-outlined" style="font-size: 10px; margin-bottom: 2px;">${prefix}elevation${suffix} Elevation: N/A (Data unavailable)`;const markerElement=document.createElement('div');markerElement.className='marker';const markerLine=document.createElement('div');markerLine.className='marker-line';const markerCircle=document.createElement('div');markerCircle.className='marker-circle';const markerLabel=document.createElement('div');markerLabel.className='marker-label';markerLabel.innerHTML=`<span class="material-symbols-outlined" style="margin-top: 0px;">psychiatry</span> <span>${location.farmname}</span><br>${elevationDisplay}`;markerElement.appendChild(markerLabel);markerElement.appendChild(markerLine);markerElement.appendChild(markerCircle);const farmDetails=farms.flatMap(farm=>farm).find(farm=>farm.farm_name===location.farmname);const imageUrl=getRandomImageUrl();const farmArea=farmDetails?farmDetails.farm_area:'N/A';const farmId=farmDetails?farmDetails.farm_id:'N/A';const region=location.region_name;const farmAddress=farmDetails?farmDetails.farm_address:'N/A';pointCounter++;counterElement.innerHTML=`
                    <span class="material-symbols-outlined" style="font-size: 30px; vertical-align: middle;">psychiatry</span>
                    <span style="font-size:40px; position: relative; top: 2px;">
                        ${uniqueFarmCount} <span data-translate="farms">trang trại</span>
                    </span>
                `;counterElement.style.marginTop='10px';let popupContent=`
                  <div style="position: relative; padding: 0; margin: 0; padding-bottom: 10px;">
                    <div style="overflow: hidden; width: 242px; height: 150px; position: relative; margin-left: -5%; margin-top: -13px; border-top-left-radius: 6px; border-top-right-radius: 6px;" onmouseover="this.querySelector('.parallax-img').style.transform = 'scale(1.1)'" onmouseout="this.querySelector('.parallax-img').style.transform = 'scale(1)'">
                      <img src="${randomImage}" alt="Farm Image" style="width: 303px; height: 150px; position: absolute; top: 0; left: 0; transition: transform 0.3s ease;" class="parallax-img" />
                    </div>
                    
                    <div style="position: absolute; top: 30px; left: 0px; color: white; text-shadow: 2px 2px 4px rgba(0,0,0,0.5);">
                      <span class="material-symbols-outlined" style="font-size: 16px; margin-right: 2px; color: white;">psychiatry</span>
                      <b style="font-size: 17px; color: white;">${location.farmname}</b><br>
                      <span class="material-symbols-outlined" style="font-size: 10px; margin-right: 4px; color: white;">location_on</span>
                      <span style="font-size: 11px; color: white;">${farmDetails ? farmDetails.farm_address || 'N/A' : 'N/A'}</span><br>
                    </div>
                  </div>
                  
                  <div style="padding-bottom: 30px; top-padding 0px">
                    <div>
                      <!--Farm ID: ${farmDetails ? farmDetails.farm_id : 'N/A'}<br>-->
                      <!--Region name: ${location.region_name}<br>-->
                `;if(farmDetails){const matchingCultivates=farmDetails.cultivates.filter(cultivate=>cultivate.name===location.region_name);if(matchingCultivates.length>0){popupContent+=`
                            <span class="material-symbols-outlined" style="font-size: 14px; margin-right: 2px;">elevation</span> <b data-translate="Elevation">${getTranslatedText("Elevation")}</b>: ${elevation.toFixed(0)} meters<br>

                      <span class="material-symbols-outlined" style="font-size: 14px; vertical-align: -2px;">grid_on</span> <b data-translate="Farm Area">${getTranslatedText("Farm Area")}</b>: ${farmDetails.farm_area} ha.
                      <!--Cultivate IDs: ${matchingCultivates.map(cultivate => cultivate.cultivate_id).join(', ')}-->
                    `;const cultivateDetailsPromises=matchingCultivates.map(async cultivate=>{popupContent+=`
                        <br>
                        <span class="material-symbols-outlined" style="font-size: 14px; vertical-align: -2px;"><b>psychiatry</span> <span data-translate="Tree Type">Loại cây</span>:</b> ${cultivate.tree_type === 0 ?
                            '<img src="https://i.ibb.co/n0wJnyq/icons8-coffee-beans-48.png" alt="Coffee Beans" style="width: 10px;"> <span data-translate="Coffee">Cà phê</span>' :
                            cultivate.tree_type === 1 ?
                                '<img src="https://i.ibb.co/gV8W7kL/icons8-durian-64.png" alt="Durian" style="width: 10px;"> <span data-translate="Durian">Sầu riêng</span>' :
                                cultivate.tree_type === 2 ?
                                    '<img src="https://i.ibb.co/WxVZrLN/icons8-pepper-96.png" alt="Pepper" style="width: 10px;"> <span data-translate="Pepper">Tiêu</span>' :
                                    cultivate.tree_type === 3 ?
                                        '<img src="https://i.ibb.co/RCnz5gb/icons8-tea-leaves-64.png" alt="Tea" style="width: 10px;"> <span data-translate="Tea">Trà</span>' :
                                        'N/A'
                        }<br>`;const cultivateDetails=await fetch(`https://api-router.enfarm.com/api/v3/cultivate/retrieve-cultivate-tree`,{method:'POST',headers:{'accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({cultivate_id:cultivate.cultivate_id})}).then(response=>response.json()).then(data=>data.content).catch(error=>{console.error(`Error fetching cultivate details for cultivate_id ${cultivate.cultivate_id}:`,error);return null;});if(cultivateDetails){popupContent+=`
                          <div>
                          <span class="material-symbols-outlined" style="font-size: 14px; vertical-align: -2px;">trending_flat</span><b> <span data-translate="Current Productivity">Năng suất hiện tại</span>: <span class="material-symbols-outlined" style="font-size: 16px; vertical-align: middle; position: relative; top: -2px;">weight</span></b>${cultivateDetails.current_prod} tonnes<br>      
                          <span class="material-symbols-outlined" style="font-size: 14px; vertical-align: -2px;">trending_up</span><b> <span data-translate="Expected Productivity">Năng suất dự kiến</span>: <span class="material-symbols-outlined" style="font-size: 16px; vertical-align: middle; position: relative; top: -2px;">weight</span></b>${cultivateDetails.expected_prod} tonnes<br>
                  
                            
                            
                            <!--Region ID: ${cultivateDetails.region_id}<br>-->
                            <!--Softids:<br>-->
                            <br>
                            <span class="soildata-pill" style="background-color: #4CAF50; color: white; padding: 3px 10px; border-radius: 20px; font-size: 12px; cursor: pointer; display: inline-flex; align-items: center; height: 25px; float: right; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); transition: background-color 0.3s;" onclick="toggleSoilData(this)" onmouseover="this.style.backgroundColor='#006400'" onmouseout="this.style.backgroundColor='#4CAF50'">
                              <i class="material-symbols-outlined" style="margin-right: 3px; font-size: 16px;">science</i>
                              <span class="toggle-text" style="white-space: nowrap;" data-translate="View soil data">Xem dữ liệu đất</span>
                              <span class="tooltip-bottom" data-translate="See detailed soil data available">See detailed soil data available</span>
                            </span>                
                            <div class="soil-data" style="display:none;">
                              <br>
                              <br>
                              <br>
                        `;totalCurrentProd+=cultivateDetails.current_prod;totalExpectedProd+=cultivateDetails.expected_prod;const nutritionDataPromises=cultivateDetails.softids.map(async softid=>{try{const nutritionData=await fetch(`https://api-router.enfarm.com/api/v3/charts/retrieve-nutrition-chart-old`,{method:'POST',headers:{'accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({region_id:cultivateDetails.region_id})}).then(response=>response.json()).then(data=>{const matchingValues=data.content.find(item=>item.in_depth===softid.in_depth)?.values;if(matchingValues){const combinedValues=matchingValues.created_at.map((createdAt,index)=>({created_at:new Date(createdAt),npk:matchingValues.npk[index],moist:matchingValues.moist[index],pH:matchingValues.pH[index],t:matchingValues.t[index]}));combinedValues.sort((a,b)=>b.created_at-a.created_at);const latestData=combinedValues[0];return{npk:latestData.npk,moist:latestData.moist,pH:latestData.pH,t:latestData.t,created_at:latestData.created_at.toISOString(),};}
return null;}).catch(error=>{console.error(`Error fetching nutrition data for region_id ${cultivateDetails.region_id} and in_depth ${softid.in_depth}:`,error);return null;});if(nutritionData){const circleColorTemp=nutritionData.t<20?"#BA0F30":(nutritionData.t<=30?"#18A558":"#BA0F30");const circleColorpH=nutritionData.pH<7?"#BA0F30":(nutritionData.pH===7?"#18A558":"#BA0F30");const circleColorMoist=(nutritionData.moist<=22.5||nutritionData.moist>55)?"#BA0F30":(nutritionData.moist<=55?"#18A558":"#BA0F30");const npkQuotient=nutritionData.npk/300;const circleColorNPK=npkQuotient<0.5?"#BA0F30":(npkQuotient<=1?"#18A558":"#BA0F30");const roundedValue=(value)=>value!==null?value.toFixed(2):'null';if(circleColorTemp==='#BA0F30'||circleColorpH==='#BA0F30'||circleColorMoist==='#BA0F30'||circleColorNPK==='#BA0F30'){farmsNeedingAttention.add(location.farmname);}
popupContent+=`
                                <div style="position: relative; display: flex; align-items: center;">
                                <span data-translate="In Depth">Chiều sâu</span>: ${softid.in_depth} (${softid.in_depth_label})
                                  <span class="material-symbols-outlined showHistoricalSoilData-btn" style="position: absolute; right: 0; font-size: 20px; cursor: pointer;" data-region-id="${cultivateDetails.region_id}" data-in-depth="${softid.in_depth}" title="Show historical soil data">chevron_forward</span>
                                </div>
                                
                                <div style="display: flex; flex-wrap: wrap;">
                                  <div style="flex: 1 1 42%;">
                                    <span class="material-symbols-outlined" style="font-size: 11px; margin-right: -1px;">bubble_chart</span>
                                    <b>NPK:</b> ${roundedValue(nutritionData.npk)}&nbsp;&nbsp;${nutritionData.npk !== null ? `<i class="fas fa-circle"style="color: ${circleColorNPK}; font-size: 9px; ${circleColorNPK === '#BA0F30' ? 'animation: glowRed 1s infinite;' : ''}"></i>` : ''}<br>
                                    <span class="material-symbols-outlined" style="font-size: 11px; margin-right: -1px;">humidity_mid</span>
                                    <b data-translate="Moist">Độ ẩm</b>: ${roundedValue(nutritionData.moist)}${nutritionData.moist !== null ? `&nbsp;<i class="fas fa-circle"style="color: ${circleColorMoist}; font-size: 9px; ${circleColorMoist === '#BA0F30' ? 'animation: glowRed 1s infinite;' : ''}; margin-left: 0px;"></i>` : ''}<br>
                                  </div>
                                  <div style="flex: 1 1 50%;">
                                  <span class="material-symbols-outlined" style="font-size: 11px; margin-right: -1px; margin-left: 7px;">water_ph</span>
                                  <b>pH:</b> ${roundedValue(nutritionData.pH)}&nbsp;&nbsp;${nutritionData.pH !== null ? `<i class="fas fa-circle"style="color: ${circleColorpH}; font-size: 9px; ${circleColorpH === '#BA0F30' ? 'animation: glowRed 1s infinite;' : ''}"></i>` : ''}<br>    
                                  <span class="material-symbols-outlined" style="font-size: 11px; margin-right: -1px; margin-left: 7px;">device_thermostat</span>
                                  <b data-translate="Temp">Nhiệt độ</b>: ${roundedValue(nutritionData.t)}${nutritionData.t !== null ? `&nbsp;<i class="fas fa-circle"style="color: ${circleColorTemp}; font-size: 9px; ${circleColorTemp === '#BA0F30' ? 'animation: glowRed 1s infinite;' : ''}; margin-left: 0px;"></i>` : ''}<br>
                                </div>
                              </div>
                              <span style="font-size: 9px;">
                                <i class="material-symbols-outlined" style="vertical-align: middle; font-size: 12px;">schedule</i>
                                <i style="vertical-align: middle;"><span data-translate="Last updated">Cập nhật mới nhất</span>: ${nutritionData.created_at}</i>
                              </span><br><br>
                              <style>
                                @keyframes glowRed {
                                  0% { color: #BA0F30; text-shadow: 0 0 5px #e86161, 0 0 10px #e86161, 0 0 15px #e86161; }
                                  50% { color: #e86161; text-shadow: 0 0 10px #e86161, 0 0 20px #e86161, 0 0 30px #e86161; }
                                  100% { color: #BA0F30; text-shadow: 0 0 5px #e86161, 0 0 10px #e86161, 0 0 15px #e86161; }
                                }
                              </style>
                            `;}else{}}catch(error){console.error(`Error processing nutrition data for softid ${softid.in_depth}:`,error);}});await Promise.all(nutritionDataPromises);popupContent+=`</div></div>`;}else{popupContent+=`<br><i>Error fetching cultivate details</i>`;}
return popupContent;});await Promise.all(cultivateDetailsPromises);}else{popupContent+=`<i>No matching cultivate details found</i><br>`;}}else{popupContent+=`<i>Farm details not found</i><br>`;}
document.getElementById('totalDevicesCount').innerText=totalDevicesCount;document.getElementById('needAttentionSum').innerText=farmsNeedingAttention.size;document.getElementById('totalDevicesCountFraction').innerText=uniqueFarmCount;document.getElementById('currentProductivitySum').innerText=totalCurrentProd.toFixed(2);document.getElementById('expectedProductivitySum').innerText=totalExpectedProd.toFixed(2);const popup=new mapboxgl.Popup().setHTML(popupContent);const marker=new mapboxgl.Marker(markerElement).setLngLat([location.long,location.lat]).setPopup(popup).addTo(map);popup.on('open',function(){const showHistoricalSoilDataBtns=this._content.querySelectorAll('.showHistoricalSoilData-btn');if(showHistoricalSoilDataBtns){showHistoricalSoilDataBtns.forEach(btn=>{if(!btn.getAttribute('data-event-added')){const handleClick=function(){const regionId=this.getAttribute('data-region-id');const inDepth=this.getAttribute('data-in-depth');console.log("region_id:",regionId);console.log("depth_id:",inDepth);fetchData(regionId,inDepth);const event=new CustomEvent('soilDataRequested',{detail:{regionId:regionId,depthId:inDepth}});window.dispatchEvent(event);const popupHistoricalSoilData=document.getElementById('popup-historicalsoildata');popupHistoricalSoilData.style.display='block';};btn.addEventListener('click',handleClick);btn.setAttribute('data-event-added','true');}});}});});}).catch(error=>console.error('Error fetching installation locations:',error));}catch(error){console.error('Error fetching farm details:',error);}};function toggleSoilData(element){var soilDataDiv=element.nextElementSibling;var toggleText=element.querySelector('.toggle-text');if(soilDataDiv.style.display==="none"){soilDataDiv.style.display="block";toggleText.textContent=getTranslatedText('Hide soil data');}else{soilDataDiv.style.display="none";toggleText.textContent=getTranslatedText('View soil data');}}
function updateOpenPopup(){map.eachLayer(function(layer){if(layer instanceof L.Marker&&layer.isPopupOpen()){const popup=layer.getPopup();const content=popup.getContent();const tempDiv=document.createElement('div');tempDiv.innerHTML=content;const elementsToTranslate=tempDiv.querySelectorAll('[data-translate]');elementsToTranslate.forEach(element=>{const key=element.getAttribute('data-translate');element.textContent=getTranslatedText(key);});const historicalSoilDataBtns=tempDiv.querySelectorAll('.showHistoricalSoilData-btn');historicalSoilDataBtns.forEach(btn=>{const regionId=btn.querySelector('.material-symbols-outlined').getAttribute('data-region-id');const inDepth=btn.querySelector('.material-symbols-outlined').getAttribute('data-in-depth');btn.querySelector('.material-symbols-outlined').setAttribute('data-region-id',regionId);btn.querySelector('.material-symbols-outlined').setAttribute('data-in-depth',inDepth);});const updatedContent=tempDiv.innerHTML;popup.setContent(updatedContent);popup.update();const popupContainer=popup.getElement();if(popupContainer){const showHistoricalSoilDataBtns=popupContainer.querySelectorAll('.showHistoricalSoilData-btn');showHistoricalSoilDataBtns.forEach((btn)=>{btn.removeEventListener('click',handleHistoricalSoilDataClick);btn.addEventListener('click',handleHistoricalSoilDataClick);});}}});}
let pointCounter=0;const counterElement=document.createElement('div');counterElement.className='point-counter';counterElement.innerHTML=`
<div style="margin-top: 20px;">
    <span class="material-symbols-outlined" style="font-size: 30px; vertical-align: middle;">psychiatry</span>
    <span style="font-size: 35px; position: relative; top: 2px;">${pointCounter} <span data-translate="farms">farms</span></span>
</div>
`;map.getContainer().appendChild(counterElement);const hectaresElement=document.createElement('div');hectaresElement.className='hectares-counter';hectaresElement.innerHTML=`<span class="material-symbols-outlined">background_dot_small</span> <span id="hectaresCount">Loading...</span> hectares`;document.body.appendChild(hectaresElement);fetchFarmData3D(authenticatedUserIDs);