let userFarms=[];let suggestionsContainer;let currentSuggestions=[];const searchInput=document.getElementById('searchInput');const API_ENDPOINTS={USER_FARMS:'https://api-router.enfarm.com/api/v3/farm/total-farms-per-user',ALL_LOCATIONS:'https://api-ma.enfarm.com/api/v1/ma/get-install-locations'};const CONFIG={MAX_SUGGESTIONS:10};async function fetchUserFarms(){const userIDsRaw=localStorage.getItem('userId');if(!userIDsRaw){console.error('User ID(s) not found in localStorage');return;}
let userIDs;try{userIDs=JSON.parse(userIDsRaw);}catch(e){userIDs=userIDsRaw.split(',').map(id=>id.trim());}
const userIDArray=Array.isArray(userIDs)?userIDs:[userIDs];userFarms=userIDArray.includes('admin')?await fetchAllUserFarms():await fetchFarmsForUsers(userIDArray);}
async function fetchAllUserFarms(){const allUserIDs=[236,260,261,990,1454];return await fetchFarmsForUsers(allUserIDs);}
async function fetchFarmsForUsers(userIDs){const validUserIDs=userIDs.filter(id=>!isNaN(parseInt(id)));const promises=validUserIDs.map(async userID=>{const options={method:'POST',headers:{'accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({user_id:parseInt(userID)})};try{const response=await fetch(API_ENDPOINTS.USER_FARMS,options);const responseData=await response.json();if(response.ok&&responseData.status_code===200&&responseData.content&&responseData.content.data){return responseData.content.data;}else{console.error(`Error fetching farms for user ID ${userID}:`,responseData);return[];}}catch(error){console.error(`Error fetching farms for user ID ${userID}:`,error);return[];}});const results=await Promise.all(promises);return results.flat();}
async function initializeSearch(){await fetchUserFarms();setupEventListeners();}
function setupEventListeners(){suggestionsContainer=document.getElementById('suggestionsContainer');if(searchInput){searchInput.addEventListener('input',handleInput);searchInput.addEventListener('keypress',handleKeyPress);}else{console.error("Search input element not found");}
if(suggestionsContainer){suggestionsContainer.addEventListener('click',handleSuggestionClick);}else{console.error("Suggestions container not found");}
const clearButton=document.querySelector('.clear-button');if(clearButton){clearButton.addEventListener('click',clearSearch);}else{console.error("Clear button not found");}
document.addEventListener('click',hideSuggestionsOnOutsideClick);}
function handleInput(){const clearButton=document.querySelector('.clear-button');if(searchInput.value.trim()!==''){clearButton.style.display='block';}else{clearButton.style.display='none';}
debounce(showSuggestions,300)();}
function clearSearch(){searchInput.value='';document.querySelector('.clear-button').style.display='none';suggestionsContainer.style.display='none';searchInput.focus();}
const debounce=(func,delay)=>{let timeoutId;return(...args)=>{clearTimeout(timeoutId);timeoutId=setTimeout(()=>func.apply(this,args),delay);};};function showSuggestions(){const searchTerm=searchInput.value.toLowerCase().trim();if(searchTerm.length===0){suggestionsContainer.style.display='none';currentSuggestions=[];return;}
currentSuggestions=userFarms.filter(farm=>farm.farm_name.toLowerCase().includes(searchTerm)).slice(0,CONFIG.MAX_SUGGESTIONS);suggestionsContainer.innerHTML=currentSuggestions.length>0?currentSuggestions.map(farm=>`
            <div class="suggestion" data-farm-id="${farm.farm_id}">
                <span class="material-symbols-outlined">psychiatry</span>
                <span>${farm.farm_name}</span>
            </div>
        `).join(''):`<div class="suggestion no-result">
            <span class="material-symbols-outlined">error_outline</span>
            <span>No result</span>
        </div>`;suggestionsContainer.style.display='block';}
function handleSuggestionClick(e){const suggestionElement=e.target.closest('.suggestion');if(!suggestionElement||suggestionElement.classList.contains('no-result'))return;const selectedFarmName=suggestionElement.querySelector('span:last-child').textContent;searchInput.value=selectedFarmName;suggestionsContainer.style.display='none';const selectedFarm=userFarms.find(farm=>farm.farm_name===selectedFarmName);if(selectedFarm){flyToFarm(selectedFarm);}}
function handleKeyPress(event){if(event.key==='Enter'){suggestionsContainer.style.display='none';if(currentSuggestions.length===1){selectSingleSuggestion();}else{searchFeatures(searchInput.value);}}}
function selectSingleSuggestion(){const singleFarm=currentSuggestions[0];searchInput.value=singleFarm.farm_name;flyToFarm(singleFarm);}
async function flyToFarm(farm){try{const response=await fetch(API_ENDPOINTS.ALL_LOCATIONS);const data=await response.json();if(data.status_code===200&&data.content){const farmLocation=data.content.find(location=>location.farmid===farm.farm_id);if(farmLocation){map.flyTo({center:[farmLocation.long,farmLocation.lat],zoom:15,essential:true});}else{console.error(`Coordinates not found for farm: ${farm.farm_name}`);alert(`Unable to locate ${farm.farm_name}. Please try another search.`);}}else{throw new Error('Unexpected API response');}}catch(error){console.error('Error fetching location data:',error);alert('An error occurred while trying to locate the farm. Please try again later.');}}
async function searchFeatures(query){const clearButton=document.querySelector('.clear-button');if(query.trim()!==''){clearButton.style.display='block';}else{clearButton.style.display='none';}
try{const response=await fetch(API_ENDPOINTS.ALL_LOCATIONS);const data=await response.json();const filteredLocations=data.content.filter(location=>{return location.farmname.toLowerCase().includes(query.toLowerCase());});if(filteredLocations.length>0){}else{alert("No match found");}}catch(error){console.error('Error fetching or processing data:',error);}}
function hideSuggestionsOnOutsideClick(e){if(suggestionsContainer&&searchInput&&e.target!==searchInput&&!suggestionsContainer.contains(e.target)){suggestionsContainer.style.display='none';}}
initializeSearch();